# Generated by Django 2.1.5 on 2019-02-25 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190225_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 9, 54, 26, 615895, tzinfo=utc)),
        ),
    ]
